name: "Application Testing" # Pipeline name.

on: 
  push: # Trigger on push events.
    branches: 
      - release # Only on 'release' branch.
  pull_request: # Trigger on pull requests.
    branches:
      - release # Only for 'release' branch.

jobs:
  Testing: # Job for testing.
    runs-on: ubuntu-latest # Use the latest Ubuntu runner.
    steps:
      - name: Checkout code # Clone the repo.
        uses: actions/checkout@v3

      - name: Set up PHP # Configure PHP.
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Set PHP version.
          extensions: mbstring, pdo, bcmath # Required extensions.
          ini-values: post_max_size=256M, upload_max_filesize=256M # Custom PHP settings.
          coverage: none # No coverage report.

      - name: Install composer packages
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
        
      - name: Create .env file
        run: cp .env.example .env
        
      - name: Generate application key
        run: php artisan key:generate
        
      - name: Run migrations
        run: php artisan migrate --env=testing
      
      -name: Testing
        run: php artisan test
